/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutOfCatalogRouteImport } from './routes/out-of-catalog'
import { Route as IndexRouteImport } from './routes/index'

const OutOfCatalogRoute = OutOfCatalogRouteImport.update({
  id: '/out-of-catalog',
  path: '/out-of-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/out-of-catalog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/out-of-catalog'
  id: '__root__' | '/' | '/out-of-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutOfCatalogRoute: typeof OutOfCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/out-of-catalog': {
      id: '/out-of-catalog'
      path: '/out-of-catalog'
      fullPath: '/out-of-catalog'
      preLoaderRoute: typeof OutOfCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutOfCatalogRoute: OutOfCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
