/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as OutOfCatalogRouteImport } from './routes/out-of-catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicUnlockRouteImport } from './routes/api/public/unlock'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const OutOfCatalogRoute = OutOfCatalogRouteImport.update({
  id: '/out-of-catalog',
  path: '/out-of-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnlockRoute = ApiPublicUnlockRouteImport.update({
  id: '/api/public/unlock',
  path: '/api/public/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
  '/sandbox': typeof SandboxRoute
  '/unlock': typeof UnlockRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
  '/sandbox': typeof SandboxRoute
  '/unlock': typeof UnlockRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/out-of-catalog': typeof OutOfCatalogRoute
  '/sandbox': typeof SandboxRoute
  '/unlock': typeof UnlockRoute
  '/api/public/unlock': typeof ApiPublicUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/out-of-catalog'
    | '/sandbox'
    | '/unlock'
    | '/api/public/unlock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/out-of-catalog' | '/sandbox' | '/unlock' | '/api/public/unlock'
  id:
    | '__root__'
    | '/'
    | '/out-of-catalog'
    | '/sandbox'
    | '/unlock'
    | '/api/public/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutOfCatalogRoute: typeof OutOfCatalogRoute
  SandboxRoute: typeof SandboxRoute
  UnlockRoute: typeof UnlockRoute
  ApiPublicUnlockRoute: typeof ApiPublicUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out-of-catalog': {
      id: '/out-of-catalog'
      path: '/out-of-catalog'
      fullPath: '/out-of-catalog'
      preLoaderRoute: typeof OutOfCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unlock': {
      id: '/api/public/unlock'
      path: '/api/public/unlock'
      fullPath: '/api/public/unlock'
      preLoaderRoute: typeof ApiPublicUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutOfCatalogRoute: OutOfCatalogRoute,
  SandboxRoute: SandboxRoute,
  UnlockRoute: UnlockRoute,
  ApiPublicUnlockRoute: ApiPublicUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
